### ISSUE TITLE
Not Working for me on Windows

### ISSUE THREAD

**Issue by atb-brown** [alexmarqs/springboot-rest-api-mongodb#1]
I'm not an expert, especially not on Docker, but this isn't working for me on Windows. I also tried in powershell, but no luck.

I'm getting this error `/bin/sh: 1: ./mvnw: not found`

I also tried modifying the `Dockerfile` and changing from `mvnw` to `mvnw.cmd` but it gives other errors and, I'm guessing, it was a stupid thing to try in the first place.

**Comment by alexmarqs** [comment]
Hey @atb-brown, the issue that you are having in your Window machine(Win 10?) could be related with some windows line endings (`\r\n` called CRLF) or something similar in your `mvnw` script (and consequently it will not be parsed as Linux file). When you clone the repository the git for Windows may change the line endings to CRLF  :neutral_face:.

Some possible solutions:
1) If you have installed the **Notepad++** : Open the mvnw script and then go to ` Edit -> EOL Conversion -> Unix`, save the file and try again. Alternatively you can also try to Find for = \r\n and then Replace with = \n (do this for all the occurrences); 
2) Using **Powershell** (not tested): ``(Get-Content $file -Raw).Replace("`r`n","`n") | Set-Content $file -Force`` where `$file = 'path\to\your\file'`;
3) Using a tool like **dos2unix** to replace \r\n with \n;

I hope this helps, just let me know if it worked.

**Comment by atb-brown** [comment]
Hello @alexmarqs! Thanks for the help. First off, yes, I'm using Windows 10. :)

And I will try this real quick! That definitely sounds like it could be an issue. I'll report back after I work on this a little.

**Comment by atb-brown** [comment]
Looks like that worked for me! (I went with the Notepad++ method.) The service is up and running, at least.

However, now I'm getting an issue with the actual API. I'm sending a post request:
```
http://localhost:8080/campaigns

->

{
    "Campaign" : {
        "Name" : "campaign name",
        "Description" : "It's a campaign.",
        "Email" : "a.b@c.com"
    }
}
```

And I'm getting a BAD_REQUEST response saying that the description, email, and name are mandatory even though I've supplied them:
```
{
    "status": "BAD_REQUEST",
    "message": "Validation errors",
    "errors": [
        "Description is mandatory",
        "Email is mandatory",
        "Name is mandatory"
    ]
}
```


I've looked around in the code and while I see these being enforced in the `Campaign` POJO, I can't see anywhere else where these might be thrown so I'm not sure what else I might be doing wrong.

## 

And this is unrelated, but I see this every time I try setting up services with spring/docker/mongo, but I get this exception in the rest (not the mongo) container:
```
2021-01-25T16:09:56.598+0000 INFO Exception in monitor thread while connecting to server my_mongodb:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
 at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar!/:?]
 at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar!/:?]
 at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) [mongodb-driver-core-3.8.2.jar!/:?]
 at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
 at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
 at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
 at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
 at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
 at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
 at java.net.Socket.connect(Unknown Source) ~[?:?]
 at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar!/:?]
 at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar!/:?]
... 3 more
```

I'm not sure if this is something you're seeing, too, but I figured I'd ask about it to see if you knew anything about it. :)

**Comment by alexmarqs** [comment]
Hey again @atb-brown , ok I will close then this issue, that's clarified :). Regarding your other(s) question(s):

For the REST HTTP request that you want you need to send the following payload object 
```
{
  "name" : "campaign name",
  "description" : "It's a campaign",
  "email" : "a.b@c.com"
}
```
Reason: you need to use the same structure as the POJO Campaign model / DTO (data transfer object), otherwise it will fail to validation or during JSON deserialisation.  

For your last question (not directly related in the original doubt/issue), I need to have more information about the exactly commands that you running to try to help you. At least I didn't have this problem.
